name: CI
on:
  pull_request:
    branches: [main]
  workflow_dispatch:
permissions:
  contents: read
jobs:
  ci:
    uses: rockman88v/platform-ci-cd/.github/workflows/reusable-ci.yaml@main
    with:
      dotnet-version: 3.1.100
      solution: ./PlayStudios.MyService/PlayStudios.MyService.sln
      test-project: ./PlayStudios.MyService/PlayStudios.MyService.WebApi.Tests/PlayStudios.MyService.WebApi.Tests.csproj
      configuration: Release
      coverage-enabled: true
      security-scan-enabled: true
      trivy-fail-on-vulnerability: false
    secrets: inherit
